In [2]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [4]:
np.arange(0, 20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [8]:
a = np.array([[1,2],[3,4]])

In [9]:
np.transpose(a
             )

array([[1, 3],
       [2, 4]])

In [10]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [11]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]
