In [2]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [4]:
np.arange(0, 20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [8]:
a = np.array([[1,2],[3,4]])

In [9]:
np.transpose(a
             )

array([[1, 3],
       [2, 4]])

In [10]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [1]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [2]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,32,93,39]))
demo_matrix[2,3]

39

In [3]:
import pandas as pd
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

In [4]:
pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

In [5]:
import numpy as np
demo_array = np.arange(10,17)
demo_array [:]= 101
demo_array


array([101, 101, 101, 101, 101, 101, 101])

In [6]:
import pandas as pd
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [8]:
!pip install seaborn

     ---------------------------------------- 0.0/293.3 kB ? eta -:--:--
     - -------------------------------------- 10.2/293.3 kB ? eta -:--:--
     --------------- ---------------------- 122.9/293.3 kB 1.8 MB/s eta 0:00:01
     -------------------------------------  286.7/293.3 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 293.3/293.3 kB 1.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: C:\Users\rers9\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [9]:
import pandas
import seaborn as sns
data=sns.load_dataset('tips')

In [12]:
pd.pivot_table(data=data, values='total_bill', index='sex', columns='day', aggfunc='mean')

day,Thur,Fri,Sat,Sun
sex,,,,
Male,18.714667,19.857000,20.802542,21.887241
Female,16.715312,14.145556,19.680357,19.872222


In [13]:
pandas.pivot_table(data=data, values='total_bill', index='day', columns='sex', aggfunc='mean')

sex,Male,Female
day,,
Thur,18.714667,16.715312
Fri,19.857000,14.145556
Sat,20.802542,19.680357
Sun,21.887241,19.872222


In [14]:
pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')

C:\Users\rers9\AppData\Local\Temp\ipykernel_15724\2585661749.py:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')


total_bill
sex
Male
Female
